#%RAML 0.8
title: Remark App API
baseUri: http://remark.alterego-labs.com/api/{version}
version: v1
protocols: [HTTP]
mediaType: application/json

/messages:
  displayName: Manage messages
  get:
    displayName: Messages list
    description: List of all messages
    responses:
      200:
        body:
          application/json:
            example: !include examples/messages_list.json

/users:
  displayName: Users
  /{login}:
    displayName: User
    uriParameters:
      login:
        displayName: User login
        type: string
    get:
      displayName: User
      description: Provides the information for user
      responses:
        200:
          body:
            application/json:
              example: !include examples/get_user_ok.json
              description: When user with requested login found
        404:
          body:
            application/json:
              example: !include examples/get_user_not_found.json
              description: When user with requested exists
    /messages:
      displayName: Messages list
      description: Provides messages list of concrete user
      get:
        displayName: Message list
        responses:
          200:
            description: When user with requested login found
            body:
              application/json:
                example: !include examples/messages_list.json
          404:
            description: When user with requested exists
            body:
              application/json:
                example: !include examples/get_user_not_found.json
