language: elixir
elixir:
  - 1.2.2
otp_release:
  - 18.2.1
services:
  - postgresql
before_script:
  - psql -c 'create database remark_api_test;' -U postgres
  - cp config/test.travis.exs config/test.exs
  - MIX_ENV=test mix ecto.create
  - MIX_ENV=test mix ecto.migrate
